// ============================================================
//  MPG2026 – Semester Final Examination
//  95 questions selected from the Lessons 1–11 question bank
//  by the Final Exam Committee (see MPG_Final_Exam_Committee_Report_FINAL.docx)
// ============================================================

const QUIZ_META = {
  courseID: "MPG2026",
  lessonID:   "FINAL",
  quizID:     "MPG2026_FINAL",
  title:      "Modern Pronunciation and Grammar 2026",
  subtitle:   "Semester Final Examination (Lessons 1–11)",
};

const SECTIONS = [
  { name: "Multiple Choice", questions: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55] },
  { name: "Error Identification", questions: [56,57,58,59,60,61,62,63,64,65,66,67,68,69,70] },
  { name: "Drag & Drop", questions: [71,72,73,74,75,76,77,78,79,80,81,82,83,84,85] },
  { name: "Dictation", questions: [86,87,88] },
  { name: "Dictation + Analysis", questions: [89,90,91] },
  { name: "Fill-in-the-Blank", questions: [92,93,94,95] },
];

const COMMENT_BANDS = [
  { min: 90, max: 95, comment: "Excellent. You have a strong command of English grammar across the full semester — sentence structure, tense and aspect, articles and agreement, prepositions, comparatives, and the subjunctive." },
  { min: 79, max: 89, comment: "Good work. Your grammar is solid overall. Review the specific items you missed and revisit those lessons before moving on." },
  { min: 50, max: 78, comment: "Developing. You have a working grasp of the material but made errors across several areas. Focus review time on the lessons where you missed the most questions." },
  { min: 29, max: 49, comment: "Keep working. Several core structures from this semester still need practice — revisit the lesson quizzes for the topics you found hardest." },
  { min: 0, max: 28, comment: "Work harder. Start by reviewing the foundational lessons (sentence patterns, word classes, verb tenses) before retesting on the later, more advanced material." },
];

const CLOSING_NOTE = "This final exam draws on all eleven lessons of the semester: sentence elements and patterns, word classes, verb-pattern meaning, articles and agreement, prepositions, tense and conditionals, nominalization and adjective order, relative clauses, comparatives and superlatives, and the subjunctive mood. Review the lessons tied to any questions you missed.";

const QUESTIONS = [

  // ── Multiple Choice ─────────────────────────

  {
    id: 1, type: "mc",
    bankId: "L02-Q09", examSection: "multiple-choice",
    stem: "<em>She sang the song beautiful.</em> — Which word should replace <em>beautiful</em>?",
    options: {
      A: "beauty",
      B: "beautifully",
      C: "beautify",
    },
    correct: "B",
    explanation: "<em>Beautiful</em> is an adjective but here it modifies the verb <em>sang</em>. An adverb is needed: <em>beautifully</em>.",
    lessonNumber: 2,
    sourceFolder: "MPG2026_L02_Quiz",
    sourceFile: "MPG2026_L02_Quiz/questions.js",
    originalId: 9,
  },

  {
    id: 2, type: "mc",
    bankId: "L03-Q05", examSection: "multiple-choice",
    stem: "What is the sentence pattern? <em>She made him her husband.</em>",
    options: {
      A: "SVOO",
      B: "SVOC",
      C: "SVO",
    },
    correct: "B",
    explanation: "Teacher's Insight: 'Him' and 'a good teacher' refer to the same person — she turned him into a good teacher. Equality test: him = a good teacher → YES → SVOC. / 「him」と「a good teacher」は同一人物を指しています。等号テスト：him = a good teacher → YES → SVOCです。",
    lessonNumber: 3,
    sourceFolder: "MPG2026_L03_Quiz",
    sourceFile: "MPG2026_L03_Quiz/questions.js",
    originalId: 5,
  },

  {
    id: 3, type: "mc",
    bankId: "L04-Q02", examSection: "multiple-choice",
    stem: "What does this sentence suggest?<br><br><em>He stopped to smoke.</em>",
    options: {
      A: "He quit smoking permanently.",
      B: "He was already smoking when he stopped.",
      C: "He paused what he was doing in order to smoke.",
    },
    correct: "C",
    explanation: "Teacher's Insight: stop + to-infinitive = stop one action for the purpose of doing another. He stopped walking, driving — whatever he was doing — in order to smoke. / 「stop + 不定詞」は別のことをするために一つの行動を止めることを意味します。歩いたり、運転したりするのをやめて、タバコを吸うためです。",
    lessonNumber: 4,
    sourceFolder: "Lesson 4/MPG2026_L04_Quiz",
    sourceFile: "Lesson 4/MPG2026_L04_Quiz/questions.js",
    originalId: 2,
  },

  {
    id: 4, type: "mc",
    bankId: "L02-Q12", examSection: "multiple-choice",
    stem: "<em>She speaks English very good.</em> — Which word should replace <em>good</em>?",
    options: {
      A: "goodly",
      B: "well",
      C: "better",
    },
    correct: "B",
    explanation: "<em>Good</em> is an adjective. To modify the verb <em>speaks</em>, the adverb <em>well</em> is needed.",
    lessonNumber: 2,
    sourceFolder: "MPG2026_L02_Quiz",
    sourceFile: "MPG2026_L02_Quiz/questions.js",
    originalId: 12,
  },

  {
    id: 5, type: "mc",
    bankId: "L03-Q08", examSection: "multiple-choice",
    stem: "What is the sentence pattern? <em>He called her a liar.</em>",
    options: {
      A: "SVOO",
      B: "SVC",
      C: "SVOC",
    },
    correct: "C",
    explanation: "Teacher's Insight: 'Her' and 'a liar' refer to the same person — he is saying that she IS a liar. Equality test: her = a liar → YES → SVOC. / 「her」と「a liar」は同一人物を指しており、彼女が嘘つきだと言っています。等号テスト：her = a liar → YES → SVOCです。",
    lessonNumber: 3,
    sourceFolder: "MPG2026_L03_Quiz",
    sourceFile: "MPG2026_L03_Quiz/questions.js",
    originalId: 8,
  },

  {
    id: 6, type: "mc",
    bankId: "L04-Q04", examSection: "multiple-choice",
    stem: "What does this sentence suggest?<br><br><em>Remember to lock the door before you leave.</em>",
    options: {
      A: "You already locked the door.",
      B: "You have a memory of locking the door.",
      C: "You must not forget to do this future action.",
    },
    correct: "C",
    explanation: "Teacher's Insight: remember + to-infinitive = don't forget a future responsibility. The locking has not happened yet — it is something that must be done later. / 「remember + 不定詞」は未来の義務を忘れないことを意味します。鍵をかけることはまだ起きていない、後でしなければならないことです。",
    lessonNumber: 4,
    sourceFolder: "Lesson 4/MPG2026_L04_Quiz",
    sourceFile: "Lesson 4/MPG2026_L04_Quiz/questions.js",
    originalId: 4,
  },

  {
    id: 7, type: "mc",
    bankId: "L02-Q17", examSection: "multiple-choice",
    stem: "In <em>It is important to study grammar</em>, what does <em>it</em> refer to?",
    options: {
      A: "Nothing — it is a dummy subject",
      B: "grammar",
      C: "studying",
    },
    correct: "A",
    explanation: "<em>It</em> here is a dummy (or empty) subject. The real subject is the infinitive phrase <em>to study grammar</em>.",
    lessonNumber: 2,
    sourceFolder: "MPG2026_L02_Quiz",
    sourceFile: "MPG2026_L02_Quiz/questions.js",
    originalId: 17,
  },

  {
    id: 8, type: "mc",
    bankId: "L03-Q15", examSection: "multiple-choice",
    stem: "What is the sentence pattern? <em>I found the book interesting.</em>",
    options: {
      A: "SVO",
      B: "SVOC",
      C: "SVOO",
    },
    correct: "B",
    explanation: "Teacher's Insight: 'Interesting' comes AFTER the object 'the book' and describes it. The book = interesting → SVOC. Compare Q14 — same words, different position, different pattern. / 「interesting」は目的語「the book」の後に来てそれを説明しています。the book = interesting → SVOC。Q14と比較しましょう。同じ単語でも位置が変わるとパターンが変わります。",
    lessonNumber: 3,
    sourceFolder: "MPG2026_L03_Quiz",
    sourceFile: "MPG2026_L03_Quiz/questions.js",
    originalId: 15,
  },

  {
    id: 9, type: "mc",
    bankId: "L04-Q10", examSection: "multiple-choice",
    stem: "What does this sentence suggest?<br><br><em>I saw him crossing the street.</em>",
    options: {
      A: "I saw the whole action from beginning to end.",
      B: "I caught him in the middle of the action — it was ongoing.",
      C: "I caused him to cross the street.",
    },
    correct: "B",
    explanation: "Teacher's Insight: SVO + -ing (doing) = action already in progress when perceived. The crossing was happening before and beyond my observation. / SVO + -ing（doing）= 知覚した時点ですでに進行中の行動を意味します。横断は私の観察の前から始まっていて、その後も続いていました。",
    lessonNumber: 4,
    sourceFolder: "Lesson 4/MPG2026_L04_Quiz",
    sourceFile: "Lesson 4/MPG2026_L04_Quiz/questions.js",
    originalId: 10,
  },

  {
    id: 10, type: "mc",
    bankId: "L04-Q12", examSection: "multiple-choice",
    stem: "What does this sentence suggest?<br><br><em>The teacher told us to rewrite the report.</em>",
    options: {
      A: "The rewriting definitely happened.",
      B: "The teacher instructed or directed us — but the rewriting may not have happened.",
      C: "The teacher stopped us from rewriting.",
    },
    correct: "B",
    explanation: "Teacher's Insight: tell + O + to-infinitive = direction or instruction, not guaranteed realization. The action is pointed toward but not confirmed as completed. / 「tell + 目的語 + 不定詞」= 指示や方向を示しますが、実現は保証されません。行動は示されていますが、完了したとは確認されていません。",
    lessonNumber: 4,
    sourceFolder: "Lesson 4/MPG2026_L04_Quiz",
    sourceFile: "Lesson 4/MPG2026_L04_Quiz/questions.js",
    originalId: 12,
  },

  {
    id: 11, type: "mc",
    bankId: "L04-Q19", examSection: "multiple-choice",
    stem: "What is the key difference between these two?<br><br><em>A: He went on explaining the theory.</em><br><em>B: He went on to explain the theory.</em>",
    options: {
      A: "A = he continued the same explanation; B = he moved on to something new after finishing something else.",
      B: "A = he moved on to something new; B = he continued the same explanation.",
      C: "Both sentences mean the same thing.",
    },
    correct: "A",
    explanation: "Teacher's Insight: go on + gerund = continue doing the same thing. go on + to-infinitive = finish one thing and proceed to a new, different action. / 「go on + gerund」は同じことを続けることを意味します。「go on + 不定詞」は一つのことを終えて、新しい別の行動に進むことを意味します。",
    lessonNumber: 4,
    sourceFolder: "Lesson 4/MPG2026_L04_Quiz",
    sourceFile: "Lesson 4/MPG2026_L04_Quiz/questions.js",
    originalId: 19,
  },

  {
    id: 12, type: "mc",
    bankId: "L05-Q02", examSection: "multiple-choice",
    stem: "Which sentence correctly uses the zero article?",
    options: {
      A: "A music makes me feel relaxed.",
      B: "The music makes me feel relaxed.",
      C: "Music makes me feel relaxed.",
    },
    correct: "C",
    explanation: "Teacher's Insight: 'Music' is an uncountable noun. When referring to music in general — not a specific piece or performance — no article is used. This is the zero article with generic meaning. / 「music」は不可算名詞です。特定の曲や演奏ではなく、音楽一般について話すときは冠詞を使いません。これが総称的な意味でのゼロ冠詞です。",
    lessonNumber: 5,
    sourceFolder: "Lesson 5/MPG2026_L05A_Quiz",
    sourceFile: "Lesson 5/MPG2026_L05A_Quiz/questions.js",
    originalId: 2,
  },

  {
    id: 13, type: "mc",
    bankId: "L06-Q03", examSection: "multiple-choice",
    stem: "He is ___ school now — he has class until 3pm.",
    options: {
      A: "in",
      B: "on",
      C: "by",
      D: "at",
    },
    correct: "D",
    explanation: "AT = abstract institution / function. 'At school' = there as a student (the function). 'In the school' would mean physically inside the building — a different frame entirely.",
    lessonNumber: 6,
    sourceFolder: "Lesson6/p06-quiz",
    sourceFile: "Lesson6/p06-quiz/questions.js",
    originalId: 3,
  },

  {
    id: 14, type: "mc",
    bankId: "L09-Q01", examSection: "multiple-choice",
    stem: "The researcher _____ conducted the survey presented the results.",
    options: {
      A: "whom",
      B: "who",
      C: "whose",
      D: "where",
    },
    correct: "B",
    explanation: "The relative pronoun is the subject of 'conducted' — the researcher conducted the survey. Use 'who' for a person in subject position. 'Whom' is the object form ('the researcher whom I interviewed').",
    lessonNumber: 9,
    sourceFolder: "Lesson 9/p09-quiz",
    sourceFile: "Lesson 9/p09-quiz/questions.js",
    originalId: 1,
  },

  {
    id: 15, type: "mc",
    bankId: "L05-Q09", examSection: "multiple-choice",
    stem: "A student says:<br><br>\"I saw a dog in the park yesterday.\"<br><br>Five minutes later:<br><br>\"_____ was really friendly.\"",
    options: {
      A: "A dog",
      B: "The dog",
      C: "Dogs",
      D: "Another dog",
    },
    correct: "B",
    explanation: "Teacher's Insight: The dog was introduced as 'a dog' the first time. Now that both people know which dog is meant, 'the' is used for the second mention. First mention → 'a', second mention → 'the'. / 最初は「a dog」として紹介されました。どの犬か両者が分かるようになったので、2回目は「the」を使います。初出→「a」、2回目→「the」。",
    lessonNumber: 5,
    sourceFolder: "Lesson 5/MPG2026_L05A_Quiz",
    sourceFile: "Lesson 5/MPG2026_L05A_Quiz/questions.js",
    originalId: 9,
  },

  {
    id: 16, type: "mc",
    bankId: "L06-Q08", examSection: "multiple-choice",
    stem: "Which sentence uses the correct preposition for an abstract/emotional state?",
    options: {
      A: "She is on trouble at work.",
      B: "She is in trouble at work.",
      C: "She is at trouble at work.",
      D: "She is by trouble at work.",
    },
    correct: "B",
    explanation: "IN = enclosed state. Abstract conditions that 'surround' you use IN: in trouble, in love, in debt, in danger. The spatial schema extends — you are enclosed within the condition.",
    lessonNumber: 6,
    sourceFolder: "Lesson6/p06-quiz",
    sourceFile: "Lesson6/p06-quiz/questions.js",
    originalId: 8,
  },

  {
    id: 17, type: "mc",
    bankId: "L09-Q04", examSection: "multiple-choice",
    stem: "The university _____ I studied has an excellent library.",
    options: {
      A: "where",
      B: "when",
      C: "why",
      D: "whose",
    },
    correct: "A",
    explanation: "We study AT a university — the university is a location. Use 'where': 'the university where I studied.' Compare Q5: 'the university which I visited' — visited takes a direct object, so use 'which' or 'that' there.",
    lessonNumber: 9,
    sourceFolder: "Lesson 9/p09-quiz",
    sourceFile: "Lesson 9/p09-quiz/questions.js",
    originalId: 4,
  },

  {
    id: 18, type: "mc",
    bankId: "L05-Q12", examSection: "multiple-choice",
    stem: "\"I want to be the president.\"<br><br>What does 'the' suggest?",
    options: {
      A: "any president",
      B: "a general dream",
      C: "a specific position",
      D: "an imaginary person",
    },
    correct: "C",
    explanation: "Teacher's Insight: 'The president' points to a specific, known position — not just any president. 'The' signals that both speaker and listener understand which position is meant. / 「the president」は特定の既知のポジションを指します。どの大統領でもなく、特定の一つのポジションです。「the」によって、話し手と聞き手の両方がどのポジションか分かります。",
    lessonNumber: 5,
    sourceFolder: "Lesson 5/MPG2026_L05A_Quiz",
    sourceFile: "Lesson 5/MPG2026_L05A_Quiz/questions.js",
    originalId: 12,
  },

  {
    id: 19, type: "mc",
    bankId: "L06-Q10", examSection: "multiple-choice",
    stem: "I usually go to work ___ car.",
    options: {
      A: "in",
      B: "with",
      C: "by",
      D: "on",
    },
    correct: "C",
    explanation: "BY + no article = means/method of transport. 'By car' = the method, not the vehicle. Notice: NO article. Compare: 'in a car' (you are inside it, article needed) vs. 'by car' (it is your method).",
    lessonNumber: 6,
    sourceFolder: "Lesson6/p06-quiz",
    sourceFile: "Lesson6/p06-quiz/questions.js",
    originalId: 10,
  },

  {
    id: 20, type: "mc",
    bankId: "L09-Q05", examSection: "multiple-choice",
    stem: "The university _____ I visited last year has an excellent library.",
    options: {
      A: "where",
      B: "when",
      C: "which",
      D: "whose",
    },
    correct: "C",
    explanation: "'I visited the university' — the university is the direct object of 'visited.' Use 'which' or 'that.' 'Where' is not correct here because the university is the object, not the location of the visiting.",
    lessonNumber: 9,
    sourceFolder: "Lesson 9/p09-quiz",
    sourceFile: "Lesson 9/p09-quiz/questions.js",
    originalId: 5,
  },

  {
    id: 21, type: "mc",
    bankId: "L05-Q17", examSection: "multiple-choice",
    stem: "<em>Doctors work long hours.</em><br><br>What does the absence of any article signal?",
    options: {
      A: "specific doctors",
      B: "doctors in general",
      C: "doctors mentioned earlier",
    },
    correct: "B",
    explanation: "Teacher's Insight: A plural noun with no article means we are talking about that group in general, not specific people. 'Doctors' here means the profession as a whole. Compare: 'The doctors in this hospital work long hours' (specific doctors). / 冠詞のない複数名詞はそのグループ一般について話しています。特定の人ではなく、職業全体を指します。比較：「The doctors in this hospital work long hours」（特定の医師）。",
    lessonNumber: 5,
    sourceFolder: "Lesson 5/MPG2026_L05A_Quiz",
    sourceFile: "Lesson 5/MPG2026_L05A_Quiz/questions.js",
    originalId: 17,
  },

  {
    id: 22, type: "mc",
    bankId: "L06-Q13", examSection: "multiple-choice",
    stem: "The letter was written ___ pencil.",
    options: {
      A: "with",
      B: "by",
      C: "in",
      D: "on",
    },
    correct: "C",
    explanation: "IN = medium/substance. Pencil here is uncountable (no article) — it is the material the writing exists in. Compare: 'with a pencil' (countable tool, needs 'a'). The grammar signals the frame: no article → medium → IN.",
    lessonNumber: 6,
    sourceFolder: "Lesson6/p06-quiz",
    sourceFile: "Lesson6/p06-quiz/questions.js",
    originalId: 13,
  },

  {
    id: 23, type: "mc",
    bankId: "L09-Q07", examSection: "multiple-choice",
    stem: "The reason _____ many students choose this program is its international focus.",
    options: {
      A: "where",
      B: "when",
      C: "why",
      D: "whose",
    },
    correct: "C",
    explanation: "After 'reason,' use 'why': 'the reason why many students choose this program.' 'Why' introduces the cause or reason. 'Where' is for places. 'When' is for time.",
    lessonNumber: 9,
    sourceFolder: "Lesson 9/p09-quiz",
    sourceFile: "Lesson 9/p09-quiz/questions.js",
    originalId: 7,
  },

  {
    id: 24, type: "mc",
    bankId: "L05-Q23", examSection: "multiple-choice",
    stem: "What is the difference?<br><br>\"Some students stayed after class.\" → This means:",
    options: {
      A: "all students in the class",
      B: "a few students, not specified",
      C: "one specific student",
      D: "every student",
    },
    correct: "B",
    explanation: "Teacher's Insight: 'Some' means an unspecified number — not all, not one. It does not tell us which students or exactly how many. / 「some」は不特定の数を表します。全員でも一人でもありません。どの学生か、何人かは特定されていません。",
    lessonNumber: 5,
    sourceFolder: "Lesson 5/MPG2026_L05B_Quiz",
    sourceFile: "Lesson 5/MPG2026_L05B_Quiz/questions.js",
    originalId: 3,
  },

  {
    id: 25, type: "mc",
    bankId: "L06-Q16", examSection: "multiple-choice",
    stem: "They drove ___ the desert to reach the city.",
    options: {
      A: "through",
      B: "over",
      C: "along",
      D: "across",
    },
    correct: "D",
    explanation: "ACROSS = movement over a flat 2D surface from one side to the other. A desert is open and flat — you cross it. THROUGH = 3D enclosed space (like a forest or tunnel). The spatial shape determines the preposition.",
    lessonNumber: 6,
    sourceFolder: "Lesson6/p06-quiz",
    sourceFile: "Lesson6/p06-quiz/questions.js",
    originalId: 16,
  },

  {
    id: 26, type: "mc",
    bankId: "L09-Q09", examSection: "multiple-choice",
    stem: "The researcher with _____ I worked on the project moved to Saudi Arabia.",
    options: {
      A: "whom",
      B: "that",
      C: "which",
      D: "where",
    },
    correct: "A",
    explanation: "After a preposition such as 'with,' formal English uses 'whom': 'the researcher with whom I worked.' In everyday conversation, native speakers often avoid this structure and say 'the researcher who I worked with' or simply 'the researcher I worked with.' However, when the preposition comes before the relative pronoun, 'whom' is the standard answer.",
    lessonNumber: 9,
    sourceFolder: "Lesson 9/p09-quiz",
    sourceFile: "Lesson 9/p09-quiz/questions.js",
    originalId: 9,
  },

  {
    id: 27, type: "mc",
    bankId: "L05-Q28", examSection: "multiple-choice",
    stem: "What does \"both\" mean?",
    options: {
      A: "one of two",
      B: "neither of two",
      C: "the two together",
      D: "many",
    },
    correct: "C",
    explanation: "Teacher's Insight: 'Both' means the two together — it includes both of two things, not just one. / 「both」は2つを合わせて意味します——2つのうちの1つではなく、2つとも含みます。",
    lessonNumber: 5,
    sourceFolder: "Lesson 5/MPG2026_L05B_Quiz",
    sourceFile: "Lesson 5/MPG2026_L05B_Quiz/questions.js",
    originalId: 8,
  },

  {
    id: 28, type: "mc",
    bankId: "L06-Q21", examSection: "multiple-choice",
    stem: "The secret was shared ___ the three friends.",
    options: {
      A: "between",
      B: "across",
      C: "through",
      D: "among",
    },
    correct: "D",
    explanation: "AMONG = within a group of three or more, not individually specified. BETWEEN = two specific, named entities. Three friends form a group → AMONG. Exception: 'between' can be used even for 3+ if they are each individually named.",
    lessonNumber: 6,
    sourceFolder: "Lesson6/p06-quiz",
    sourceFile: "Lesson6/p06-quiz/questions.js",
    originalId: 21,
  },

  {
    id: 29, type: "mc",
    bankId: "L05-Q49", examSection: "multiple-choice",
    stem: "Which sentence sounds natural?",
    options: {
      A: "Bread and butter are my favorite breakfast.",
      B: "Bread and butter is my favorite breakfast.",
      C: "Bread and butter were my favorite breakfast.",
      D: "Bread and butter have my favorite breakfast.",
    },
    correct: "B",
    explanation: "Teacher's Insight: When two things are treated as one unit or concept, a singular verb is used. 'Bread and butter' is one classic combination, so 'is' is correct. / 2つのものが1つのまとまりとして扱われるとき、単数動詞を使います。「bread and butter」は定番の組み合わせで一つの概念なので「is」が正解です。",
    lessonNumber: 5,
    sourceFolder: "Lesson 5/MPG2026_L05C_Quiz",
    sourceFile: "Lesson 5/MPG2026_L05C_Quiz/questions.js",
    originalId: 9,
  },

  {
    id: 30, type: "mc",
    bankId: "L06-Q26", examSection: "multiple-choice",
    stem: "She has lived here ___ 2018.",
    options: {
      A: "for",
      B: "during",
      C: "from",
      D: "since",
    },
    correct: "D",
    explanation: "SINCE = from a specific past point to NOW. Always requires perfect tense (has lived). FOR = measured duration ('for six years'). DURING = within a named period. FROM...TO = a span between two fixed points.",
    lessonNumber: 6,
    sourceFolder: "Lesson6/p06-quiz",
    sourceFile: "Lesson6/p06-quiz/questions.js",
    originalId: 26,
  },

  {
    id: 31, type: "mc",
    bankId: "L05-Q57", examSection: "multiple-choice",
    stem: "What is the key idea behind agreement in English?",
    options: {
      A: "verbs change randomly",
      B: "agreement reflects conceptualization of the subject",
      C: "plural verbs are more formal",
      D: "singular verbs are easier to pronounce",
    },
    correct: "B",
    explanation: "Teacher's Insight: Agreement is not just a mechanical rule — it reflects how speakers think about the subject. 'Bread and butter is' (one unit) vs. 'bread and cheese are' (two separate things) shows this clearly. / 一致はただの機械的なルールではなく、話者が主語をどう概念化するかを反映します。「bread and butter is」（一つのまとまり）と「bread and cheese are」（2つの別々のもの）がそれを示しています。",
    lessonNumber: 5,
    sourceFolder: "Lesson 5/MPG2026_L05C_Quiz",
    sourceFile: "Lesson 5/MPG2026_L05C_Quiz/questions.js",
    originalId: 17,
  },

  {
    id: 32, type: "mc",
    bankId: "L06-Q29", examSection: "multiple-choice",
    stem: "In spite ___ the rain, the match continued.",
    options: {
      A: "to",
      B: "for",
      C: "of",
      D: "about",
    },
    correct: "C",
    explanation: "'In spite OF' = despite. Always OF + noun phrase. NEVER a full clause directly after: 'in spite of the rain' ✓ / 'in spite of it rained' ✗. 'Despite' works the same way: despite + noun phrase.",
    lessonNumber: 6,
    sourceFolder: "Lesson6/p06-quiz",
    sourceFile: "Lesson6/p06-quiz/questions.js",
    originalId: 29,
  },

  {
    id: 33, type: "mc",
    bankId: "L06-Q30", examSection: "multiple-choice",
    stem: "He finally ___ smoking last year.",
    options: {
      A: "gave in",
      B: "gave out",
      C: "gave away",
      D: "gave up",
    },
    correct: "D",
    explanation: "'Give up' = stop trying / quit. UP = completion, finishing something entirely. Compare: gave IN (surrendered/yielded), gave OUT (distributed or stopped working), gave AWAY (donated or revealed a secret). The particle completely changes the meaning.",
    lessonNumber: 6,
    sourceFolder: "Lesson6/p06-quiz",
    sourceFile: "Lesson6/p06-quiz/questions.js",
    originalId: 30,
  },

  {
    id: 34, type: "mc",
    bankId: "L07-Q02", examSection: "multiple-choice",
    stem: "He usually works in Tokyo, but this week he ___ in Osaka.",
    options: {
      A: "works",
      B: "worked",
      C: "is working",
      D: "has worked",
    },
    correct: "C",
    explanation: "PRESENT CONTINUOUS = a temporary situation happening around now. 'This week' signals a short-term change from his usual pattern. Compare: 'He works in Tokyo' (permanent habit) vs. 'he is working in Osaka this week' (temporary).",
    lessonNumber: 7,
    sourceFolder: "Lesson 7 Tense and Aspecdt/p07-quiz",
    sourceFile: "Lesson 7 Tense and Aspecdt/p07-quiz/questions.js",
    originalId: 2,
  },

  {
    id: 35, type: "mc",
    bankId: "L08-Q02", examSection: "multiple-choice",
    stem: "The city grew very rapidly in the 1990s. The ___ of the city during that decade surprised many economists.",
    options: {
      A: "grew",
      B: "grown",
      C: "growing",
      D: "growth",
    },
    correct: "D",
    explanation: "The blank is the head of the noun phrase 'The ___ of the city.' It must be a NOUN. 'Grew' and 'grown' are verb forms. 'Growing' as a gerund would give 'The growing of the city' — unusual and informal in this structure. 'Growth' is the standard noun derived from 'grow' and the correct choice. Verb-to-noun conversions often change the word significantly: grow → growth, communicate → communication, decide → decision.",
    lessonNumber: 8,
    sourceFolder: "Lesson 8/p08-quiz",
    sourceFile: "Lesson 8/p08-quiz/questions.js",
    originalId: 2,
  },

  {
    id: 36, type: "mc",
    bankId: "L10-Q01", examSection: "multiple-choice",
    stem: "This smartwatch is much ________ than the previous model.",
    options: {
      A: "lighter",
      B: "more lighter",
      C: "lightier",
      D: "lightest",
    },
    correct: "A",
    explanation: "One-syllable adjectives add <em>-er</em> to form the comparative. 'More lighter' is a double comparative; 'lightier' is not a word; 'lightest' is a superlative.",
    lessonNumber: 10,
    sourceFolder: "Lesson 10/p10-quiz",
    sourceFile: "Lesson 10/p10-quiz/questions.js",
    originalId: 1,
  },

  {
    id: 37, type: "mc",
    bankId: "L11-Q01", examSection: "multiple-choice",
    stem: "Choose the correct sentence.",
    options: {
      A: "If the lecture finishes early, we'll have lunch together.",
      B: "If the lecture will finish early, we'll have lunch together.",
      C: "If the lecture finished early, we'll have lunch together.",
      D: "If the lecture finishes early, we'd have lunch together.",
    },
    correct: "A",
    explanation: "Real conditionals use <em>If + present</em> in the if-clause and <em>will + verb</em> in the result clause. B wrongly puts 'will' in the if-clause; C shifts the if-clause to the past; D uses 'would', which doesn't match a real conditional.",
    lessonNumber: 11,
    sourceFolder: "Lesson 11/p11-quiz",
    sourceFile: "Lesson 11/p11-quiz/questions.js",
    originalId: 1,
  },

  {
    id: 38, type: "mc",
    bankId: "L07-Q07", examSection: "multiple-choice",
    stem: "She ___ here since 2020.",
    options: {
      A: "lived",
      B: "lives",
      C: "has lived",
      D: "was living",
    },
    correct: "C",
    explanation: "PRESENT PERFECT + SINCE = from a specific past point to NOW. The situation started in 2020 and continues to the present. 'She lived here since 2020' is wrong — simple past cannot be used with SINCE for a continuing situation. SINCE always requires the perfect.",
    lessonNumber: 7,
    sourceFolder: "Lesson 7 Tense and Aspecdt/p07-quiz",
    sourceFile: "Lesson 7 Tense and Aspecdt/p07-quiz/questions.js",
    originalId: 7,
  },

  {
    id: 39, type: "mc",
    bankId: "L08-Q19", examSection: "multiple-choice",
    stem: "A business analyst is writing a formal report. Which sentence uses the most appropriate nominalized form for written English?",
    options: {
      A: "The fact that the company expanded rapidly impressed investors.",
      B: "The company expanding rapidly impressed investors.",
      C: "The company's rapid expansion impressed investors.",
      D: "That the company expanded rapidly impressed investors.",
    },
    correct: "C",
    explanation: "All four options are grammatically possible, but they represent different levels of nominalization. Option C — *the company's rapid expansion* — is the most condensed: the whole idea is packed into a three-word noun phrase using possessive + noun. Options A and D use noun clauses ('the fact that...' / 'that...') — grammatically correct but wordy. Option B uses a gerund construction that sounds more informal. In reports and academic writing, compact possessive noun phrases are the preferred style because they are precise and clean.",
    lessonNumber: 8,
    sourceFolder: "Lesson 8/p08-quiz",
    sourceFile: "Lesson 8/p08-quiz/questions.js",
    originalId: 19,
  },

  {
    id: 40, type: "mc",
    bankId: "L10-Q09", examSection: "multiple-choice",
    stem: "Choose the sentence with the closest meaning.<br><br>This building is not taller than that one.",
    options: {
      A: "This building is as tall as that one or shorter.",
      B: "This building is shorter than that one.",
      C: "This building is exactly as tall as that one.",
      D: "This building is much shorter than that one.",
    },
    correct: "A",
    explanation: "'Not taller than' means the height is equal to or less than — it does not say which. Option B overclaims (shorter only); C overclaims (exactly equal); D adds 'much' which is not stated.",
    lessonNumber: 10,
    sourceFolder: "Lesson 10/p10-quiz",
    sourceFile: "Lesson 10/p10-quiz/questions.js",
    originalId: 9,
  },

  {
    id: 41, type: "mc",
    bankId: "L11-Q06", examSection: "multiple-choice",
    stem: "Choose the correct sentence.",
    options: {
      A: "If I were in your position, I would accept the scholarship.",
      B: "If I was in your position, I will accept the scholarship.",
      C: "If I am in your position, I would accept the scholarship.",
      D: "If I would be in your position, I would accept the scholarship.",
    },
    correct: "A",
    explanation: "Present hypothetical: <em>If + past ('were')</em>, <em>would + verb</em>. B mixes 'was' with 'will'; C keeps the if-clause in the present; D wrongly uses 'would be' in the if-clause.",
    lessonNumber: 11,
    sourceFolder: "Lesson 11/p11-quiz",
    sourceFile: "Lesson 11/p11-quiz/questions.js",
    originalId: 6,
  },

  {
    id: 42, type: "mc",
    bankId: "L07-Q09", examSection: "multiple-choice",
    stem: "By the time he got home, his wife ___ dinner.",
    options: {
      A: "cooked",
      B: "was cooking",
      C: "has cooked",
      D: "had cooked",
    },
    correct: "D",
    explanation: "PAST PERFECT = an action completed before another past event. The cooking was done BEFORE he got home. 'By the time' + past event → past perfect for the earlier action. 'Has cooked' (present perfect) cannot refer to a past moment.",
    lessonNumber: 7,
    sourceFolder: "Lesson 7 Tense and Aspecdt/p07-quiz",
    sourceFile: "Lesson 7 Tense and Aspecdt/p07-quiz/questions.js",
    originalId: 9,
  },

  {
    id: 43, type: "mc",
    bankId: "L08-Q07", examSection: "multiple-choice",
    stem: "The architect designed ___.",
    options: {
      A: "a brick beautiful old house",
      B: "an old brick beautiful house",
      C: "a beautiful brick old house",
      D: "a beautiful old brick house",
    },
    correct: "D",
    explanation: "The order is OPINION → AGE → MATERIAL: *beautiful* (how it looks — the speaker's opinion) → *old* (its age) → *brick* (what it is made of — material). 'Beautiful' comes first because it expresses the speaker's subjective response. 'Old' comes next because age is more objective than opinion. 'Brick' comes last because material is the most permanent, fixed quality — it defines the fundamental nature of the object. Options A, B, and C all place *brick* or *old* before *beautiful*, violating the opinion-first principle.",
    lessonNumber: 8,
    sourceFolder: "Lesson 8/p08-quiz",
    sourceFile: "Lesson 8/p08-quiz/questions.js",
    originalId: 7,
  },

  {
    id: 44, type: "mc",
    bankId: "L10-Q15", examSection: "multiple-choice",
    stem: "Choose the correct word.<br><br>There are ________ students in this class this year than last year.",
    options: {
      A: "less",
      B: "least",
      C: "fewer",
      D: "few",
    },
    correct: "C",
    explanation: "Use <em>fewer</em> with countable nouns (students). 'Less' is for uncountable quantities. 'Least' and 'few' are not comparative forms used with 'than'.",
    lessonNumber: 10,
    sourceFolder: "Lesson 10/p10-quiz",
    sourceFile: "Lesson 10/p10-quiz/questions.js",
    originalId: 15,
  },

  {
    id: 45, type: "mc",
    bankId: "L11-Q03", examSection: "multiple-choice",
    stem: "Choose the correct sentence.",
    options: {
      A: "If she had accepted the offer, she would have worked in London.",
      B: "If she would have accepted the offer, she would have worked in London.",
      C: "If she accepted the offer, she would have worked in London.",
      D: "If she had accepted the offer, she would work in London yesterday.",
    },
    correct: "A",
    explanation: "Past hypothetical: <em>If + had + past participle</em>, <em>would have + past participle</em>. B wrongly uses 'would have' in the if-clause too; C drops 'had'; D mixes a past if-clause with a present-tense result and 'yesterday'.",
    lessonNumber: 11,
    sourceFolder: "Lesson 11/p11-quiz",
    sourceFile: "Lesson 11/p11-quiz/questions.js",
    originalId: 3,
  },

  {
    id: 46, type: "mc",
    bankId: "L07-Q12", examSection: "multiple-choice",
    stem: "If I ___ a car, I would drive you to the airport.",
    options: {
      A: "have",
      B: "had",
      C: "would have",
      D: "am having",
    },
    correct: "B",
    explanation: "SECOND CONDITIONAL = an imaginary or unlikely present situation. Structure: If + PAST SIMPLE, would + base verb. 'Had' signals unreality — I do not actually have a car. The past tense creates distance from reality. Compare: FIRST CONDITIONAL ('if I have') = a real possibility.",
    lessonNumber: 7,
    sourceFolder: "Lesson 7 Tense and Aspecdt/p07-quiz",
    sourceFile: "Lesson 7 Tense and Aspecdt/p07-quiz/questions.js",
    originalId: 12,
  },

  {
    id: 47, type: "mc",
    bankId: "L08-Q16", examSection: "multiple-choice",
    stem: "A travel writer is describing a village. Which sentence uses the most natural adjective order?",
    options: {
      A: "We visited a small ancient Greek village.",
      B: "We visited an ancient small Greek village.",
      C: "We visited a Greek ancient small village.",
      D: "We visited a small Greek ancient village.",
    },
    correct: "A",
    explanation: "SIZE → AGE → ORIGIN: *small* (size — a general physical description) → *ancient* (age) → *Greek* (origin — a classification adjective that defines what type of village it is). Size comes before age because it is a more general physical quality. Origin sits closest to the noun because classification adjectives define the category of the noun most specifically. Option B reverses size and age. Options C and D place 'Greek' (origin) before age or size — origin should sit close to the noun, not at the start.",
    lessonNumber: 8,
    sourceFolder: "Lesson 8/p08-quiz",
    sourceFile: "Lesson 8/p08-quiz/questions.js",
    originalId: 16,
  },

  {
    id: 48, type: "mc",
    bankId: "L10-Q16", examSection: "multiple-choice",
    stem: "Choose the correct word.<br><br>There is ________ traffic on Sundays than on weekdays.",
    options: {
      A: "fewer",
      B: "few",
      C: "less",
      D: "little",
    },
    correct: "C",
    explanation: "Use <em>less</em> with uncountable nouns (traffic). 'Fewer' is for countable nouns. 'Little' and 'few' are not comparative forms used with 'than'.",
    lessonNumber: 10,
    sourceFolder: "Lesson 10/p10-quiz",
    sourceFile: "Lesson 10/p10-quiz/questions.js",
    originalId: 16,
  },

  {
    id: 49, type: "mc",
    bankId: "L07-Q15", examSection: "multiple-choice",
    stem: "If she ___ harder, she would have passed the exam.",
    options: {
      A: "studied",
      B: "had studied",
      C: "would study",
      D: "studies",
    },
    correct: "B",
    explanation: "THIRD CONDITIONAL = an imaginary past — what did not happen. Structure: If + PAST PERFECT, would have + past participle. 'Had studied' = the imaginary condition (she did NOT study enough). 'Would have passed' = the imaginary result. This expresses regret about a past situation that cannot be changed.",
    lessonNumber: 7,
    sourceFolder: "Lesson 7 Tense and Aspecdt/p07-quiz",
    sourceFile: "Lesson 7 Tense and Aspecdt/p07-quiz/questions.js",
    originalId: 15,
  },

  {
    id: 50, type: "mc",
    bankId: "L08-Q11", examSection: "multiple-choice",
    stem: "A professor teaches at Oxford University. She recently moved to another university. Choose the sentence that correctly uses a participial phrase.",
    options: {
      A: "The teaching at Oxford University professor moved to another university.",
      B: "The professor moved to another university teaching at Oxford University.",
      C: "Teaching at Oxford University the professor moved to another university.",
      D: "The professor teaching at Oxford University moved to another university.",
    },
    correct: "D",
    explanation: "A PARTICIPIAL PHRASE (more than one word) must come AFTER the noun it modifies. 'Teaching at Oxford University' is a phrase, so it follows 'the professor': *the professor teaching at Oxford University*. Option A wrongly places the phrase before 'professor' — only single-word modifiers can precede the noun. Option B places the phrase at the end of the sentence, where it describes the act of moving rather than identifying which professor. Option C creates a dangling modifier at the start of the sentence.",
    lessonNumber: 8,
    sourceFolder: "Lesson 8/p08-quiz",
    sourceFile: "Lesson 8/p08-quiz/questions.js",
    originalId: 11,
  },

  {
    id: 51, type: "mc",
    bankId: "L10-Q20", examSection: "multiple-choice",
    stem: "Choose the correct sentence.",
    options: {
      A: "This smartphone is superior than the old model.",
      B: "This smartphone is superior to the old model.",
      C: "This smartphone is more superior than the old model.",
      D: "This smartphone is superior over the old model.",
    },
    correct: "B",
    explanation: "<em>Superior</em> is a Latin-origin comparative that takes <em>to</em>, not 'than'. 'More superior' is a double comparative; 'superior over' is ungrammatical.",
    lessonNumber: 10,
    sourceFolder: "Lesson 10/p10-quiz",
    sourceFile: "Lesson 10/p10-quiz/questions.js",
    originalId: 20,
  },

  {
    id: 52, type: "mc",
    bankId: "L07-Q38", examSection: "multiple-choice",
    stem: "He didn't study. He failed the exam. Choose the sentence that expresses regret.",
    options: {
      A: "He should study harder.",
      B: "He would study harder.",
      C: "He should have studied harder.",
      D: "He must have studied harder.",
    },
    correct: "C",
    explanation: "SHOULD HAVE + past participle = regret or criticism about a past action that did NOT happen. He did not study enough — that is the regret. 'Should study' = advice for the future. 'Must have studied' = a deduction (we think he probably did study). SHOULD HAVE = the thing didn't happen, but it should have.",
    lessonNumber: 7,
    sourceFolder: "Lesson 7 Tense and Aspecdt/p07-quiz",
    sourceFile: "Lesson 7 Tense and Aspecdt/p07-quiz/questions.js",
    originalId: 38,
  },

  {
    id: 53, type: "mc",
    bankId: "L08-Q14", examSection: "multiple-choice",
    stem: "A building was damaged. It attracted photographers. Choose the sentence that correctly uses the single participial word as a modifier.",
    options: {
      A: "The building damaged attracted photographers.",
      B: "The damaged building attracted photographers.",
      C: "Damaged building the attracted photographers.",
      D: "The building attracted photographers damaged.",
    },
    correct: "B",
    explanation: "The single past participle 'damaged' goes BEFORE the noun it modifies: *the damaged building*. RULE: ONE WORD → BEFORE the noun. Option A places 'damaged' after 'building' without any complement — when a past participle stands alone after a noun with no following phrase, it is grammatically incomplete in this structure. Compare: if 'damaged' had a complement, the whole phrase would move after the noun: *the building damaged by the flood*. But when the participle is one word alone, it precedes the noun. Options C and D break basic sentence order.",
    lessonNumber: 8,
    sourceFolder: "Lesson 8/p08-quiz",
    sourceFile: "Lesson 8/p08-quiz/questions.js",
    originalId: 14,
  },

  {
    id: 54, type: "mc",
    bankId: "L10-Q27", examSection: "multiple-choice",
    stem: "Choose the correct sentence.",
    options: {
      A: "The more you practice, you become more fluent.",
      B: "More you practice, the more fluent you become.",
      C: "The more you practice, the more fluent you become.",
      D: "The more you practice, the fluenter you become.",
    },
    correct: "C",
    explanation: "The <em>the … the …</em> structure requires both clauses to begin with 'the + comparative'. 'Fluenter' is not a word; 'more fluent' is the correct form.",
    lessonNumber: 10,
    sourceFolder: "Lesson 10/p10-quiz",
    sourceFile: "Lesson 10/p10-quiz/questions.js",
    originalId: 27,
  },

  {
    id: 55, type: "mc",
    bankId: "L11-Q27", examSection: "multiple-choice",
    stem: "Choose the correct sentence.",
    options: {
      A: "But for your advice, I would have made a serious mistake.",
      B: "But for your advice, I will make a serious mistake.",
      C: "But for your advice, I had made a serious mistake.",
      D: "But for your advice, I would make a serious mistake yesterday.",
    },
    correct: "A",
    explanation: "<em>But for + noun</em> expresses a hidden unreal conditional. The result uses <em>would have + past participle</em>.",
    lessonNumber: 11,
    sourceFolder: "Lesson 11/p11-quiz",
    sourceFile: "Lesson 11/p11-quiz/questions.js",
    originalId: 27,
  },


  // ── Error Identification ────────────────────

  {
    id: 56, type: "mc",
    bankId: "L03-Q09", examSection: "error-identification",
    stem: "Choose the underlined part that contains a grammatical error.<br><br>The research <u><b>(a) conducted</b></u> by the team of scientists <u><b>(b) have produced</b></u> results that <u><b>(c) challenge</b></u> the existing <u><b>(d) theories</b></u> on climate change.",
    options: {
      A: "(a) conducted",
      B: "(b) have produced",
      C: "(c) challenge",
      D: "(d) theories",
    },
    correct: "B",
    explanation: "Teacher's Insight: The subject is 'research' (singular), so the verb should be 'has produced' not 'have produced'. Pay attention to the head noun of the subject, not the nearest noun. / 主語は「research」（単数）なので、動詞は「have produced」ではなく「has produced」が正解です。近くにある名詞ではなく、主語の中心となる名詞に注目しましょう。文の意味：科学者チームによって行われた研究は、気候変動に関する既存の理論に異議を唱える結果を生み出した。",
    lessonNumber: 3,
    sourceFolder: "MPG2026_L03_Quiz",
    sourceFile: "MPG2026_L03_Quiz/questions.js",
    originalId: 9,
  },

  {
    id: 57, type: "mc",
    bankId: "L05-Q30", examSection: "error-identification",
    stem: "Which sentence is correct?",
    options: {
      A: "Neither student were late.",
      B: "Neither students were late.",
      C: "Neither student was late.",
      D: "Neither student are late.",
    },
    correct: "C",
    explanation: "Teacher's Insight: 'Neither' (like 'either') takes a singular noun and singular verb: 'neither student was.' / 「neither」（「either」と同様）は単数名詞・単数動詞と使います。「neither student was」が正解です。",
    lessonNumber: 5,
    sourceFolder: "Lesson 5/MPG2026_L05B_Quiz",
    sourceFile: "Lesson 5/MPG2026_L05B_Quiz/questions.js",
    originalId: 10,
  },

  {
    id: 58, type: "mc",
    bankId: "L07-Q17", examSection: "error-identification",
    stem: "Which sentence is correct?",
    options: {
      A: "She is knowing the answer.",
      B: "She knows the answer.",
      C: "She has been knowing the answer.",
      D: "She was knowing the answer.",
    },
    correct: "B",
    explanation: "KNOW is a stative verb — it describes a mental state, not a developing action. Stative verbs (know, believe, understand, love, want) do not use the continuous form in standard English. 'She knows' is always correct for a permanent mental state.",
    lessonNumber: 7,
    sourceFolder: "Lesson 7 Tense and Aspecdt/p07-quiz",
    sourceFile: "Lesson 7 Tense and Aspecdt/p07-quiz/questions.js",
    originalId: 17,
  },

  {
    id: 59, type: "mc",
    bankId: "L03-Q10", examSection: "error-identification",
    stem: "Choose the underlined part that contains a grammatical error.<br><br>She remained <u><b>(a) calmly</b></u> despite the <u><b>(b) mounting</b></u> pressure from <u><b>(c) her colleagues</b></u> and <u><b>(d) supervisors</b></u>.",
    options: {
      A: "(a) calmly",
      B: "(b) mounting",
      C: "(c) her colleagues",
      D: "(d) supervisors",
    },
    correct: "A",
    explanation: "Teacher's Insight: 'Remain' is a linking verb. After a linking verb, an adjective is needed, not an adverb. 'Calmly' should be 'calm'. / 「remain」は連結動詞です。連結動詞の後には副詞ではなく形容詞が必要です。「calmly」は「calm」でなければなりません。文の意味：彼女は同僚や上司からの高まるプレッシャーにもかかわらず、冷静を保った。",
    lessonNumber: 3,
    sourceFolder: "MPG2026_L03_Quiz",
    sourceFile: "MPG2026_L03_Quiz/questions.js",
    originalId: 10,
  },

  {
    id: 60, type: "mc",
    bankId: "L08-Q20", examSection: "error-identification",
    stem: "One of these sentences has an error. Which sentence is correct?",
    options: {
      A: "Communicate effectively is essential in every workplace.",
      B: "Communication effectively is essential in every workplace.",
      C: "Communicating effectively is essential in every workplace.",
      D: "Communicated effectively is essential in every workplace.",
    },
    correct: "C",
    explanation: "The subject of a sentence must be a NOUN or noun phrase — not a bare verb. Option A (*Communicate*) is the base verb form — it cannot be the subject. Option D (*Communicated*) is the past tense — also a verb. Option B (*Communication effectively*) uses the noun 'communication,' but a noun cannot be directly modified by an adverb (*effectively*). Option C uses a GERUND PHRASE (*Communicating effectively*): gerunds are verb-noun hybrids that can take an adverb within their phrase and correctly function as subjects.",
    lessonNumber: 8,
    sourceFolder: "Lesson 8/p08-quiz",
    sourceFile: "Lesson 8/p08-quiz/questions.js",
    originalId: 20,
  },

  {
    id: 61, type: "mc",
    bankId: "L05-Q34", examSection: "error-identification",
    stem: "Which sentence is correct?",
    options: {
      A: "Every five students need one teacher.",
      B: "Every five student need one teacher.",
      C: "Every five students needs one teacher.",
      D: "Every five student needs one teacher.",
    },
    correct: "A",
    explanation: "Teacher's Insight: 'Every + number + plural noun' takes a plural verb when the phrase expresses a ratio: 'every five students need.' / 「every + 数 + 複数名詞」が比率を表す主語として機能するとき、複数動詞を使います：「every five students need」。",
    lessonNumber: 5,
    sourceFolder: "Lesson 5/MPG2026_L05B_Quiz",
    sourceFile: "Lesson 5/MPG2026_L05B_Quiz/questions.js",
    originalId: 14,
  },

  {
    id: 62, type: "mc",
    bankId: "L07-Q18", examSection: "error-identification",
    stem: "Which sentence is correct?",
    options: {
      A: "When I arrived, she already left.",
      B: "When I arrived, she has already left.",
      C: "When I arrived, she had already left.",
      D: "When I arrived, she was already left.",
    },
    correct: "C",
    explanation: "PAST PERFECT is required for an action completed BEFORE another past event. She left before I arrived — two past events in sequence. 'Had already left' makes the order clear. 'Has already left' (present perfect) cannot refer to a past moment. 'Was already left' is a passive form with a different meaning.",
    lessonNumber: 7,
    sourceFolder: "Lesson 7 Tense and Aspecdt/p07-quiz",
    sourceFile: "Lesson 7 Tense and Aspecdt/p07-quiz/questions.js",
    originalId: 18,
  },

  {
    id: 63, type: "mc",
    bankId: "L03-Q13", examSection: "error-identification",
    stem: "Choose the underlined part that contains a grammatical error, or choose (d) if there is no error.<br><br>The board <u><b>(a) unanimously</b></u> elected <u><b>(b) her</b></u> <u><b>(c) chairwoman</b></u> of the newly established international committee.",
    options: {
      A: "(a) unanimously",
      B: "(b) her",
      C: "(c) chairwoman",
      D: "(d) No error",
    },
    correct: "D",
    explanation: "Teacher's Insight: This sentence is correct. 'Elect + object + complement' (SVOC) — 'her' is the object and 'chairwoman' is the complement telling us what she became. / この文は正しいです。「elect＋目的語＋補語」（SVOC）の構文で、「her」が目的語、「chairwoman」が彼女が何になったかを示す補語です。文の意味：委員会は全会一致で彼女を新設された国際委員会の委員長に選出した。",
    lessonNumber: 3,
    sourceFolder: "MPG2026_L03_Quiz",
    sourceFile: "MPG2026_L03_Quiz/questions.js",
    originalId: 13,
  },

  {
    id: 64, type: "mc",
    bankId: "L08-Q22", examSection: "error-identification",
    stem: "One of these sentences has an error. Which sentence is correct?",
    options: {
      A: "He has a black small dog.",
      B: "He has a small black dog.",
      C: "He has a black dog small.",
      D: "He has a small dog black.",
    },
    correct: "B",
    explanation: "SIZE comes before COLOR in English adjective order: *small* (size) → *black* (color). Option A (*black small*) reverses this — placing color before size sounds unnatural. Options C and D place one adjective after the noun, separated from it: simple modifier adjectives in English must precede the noun they modify. Only B correctly orders the adjectives: *a small black dog*.",
    lessonNumber: 8,
    sourceFolder: "Lesson 8/p08-quiz",
    sourceFile: "Lesson 8/p08-quiz/questions.js",
    originalId: 22,
  },

  {
    id: 65, type: "mc",
    bankId: "L10-Q03", examSection: "error-identification",
    stem: "Which sentence contains a grammatical error?",
    options: {
      A: "This puzzle is much easier than the last one.",
      B: "Today's train is even more crowded than yesterday's.",
      C: "My new phone is more faster than my old one.",
      D: "Winter in Hokkaido is colder than in Tokyo.",
    },
    correct: "C",
    explanation: "'More faster' is a double comparative — both <em>more</em> and <em>-er</em> are used together. Use either 'faster' or 'more fast' (though 'faster' is the standard form).",
    lessonNumber: 10,
    sourceFolder: "Lesson 10/p10-quiz",
    sourceFile: "Lesson 10/p10-quiz/questions.js",
    originalId: 3,
  },

  {
    id: 66, type: "mc",
    bankId: "L05-Q44", examSection: "error-identification",
    stem: "Which sentence is correct?",
    options: {
      A: "All rice are expensive now.",
      B: "All rice is expensive now.",
      C: "All rices are expensive now.",
      D: "All rice have become expensive.",
    },
    correct: "B",
    explanation: "Teacher's Insight: 'Rice' is an uncountable noun, so it takes a singular verb. 'All rice is' is correct. There is no plural form 'rices.' / 「rice」は不可算名詞なので単数動詞を使います。「all rice is」が正解。「rices」という複数形はありません。",
    lessonNumber: 5,
    sourceFolder: "Lesson 5/MPG2026_L05C_Quiz",
    sourceFile: "Lesson 5/MPG2026_L05C_Quiz/questions.js",
    originalId: 4,
  },

  {
    id: 67, type: "mc",
    bankId: "L07-Q23", examSection: "error-identification",
    stem: "One of these sentences has an error. Which sentence is correct?",
    options: {
      A: "He didn't went to the meeting.",
      B: "He didn't go to the meeting.",
      C: "He hasn't gone to the meeting yesterday.",
      D: "He wasn't go to the meeting.",
    },
    correct: "B",
    explanation: "After the auxiliary DID, the main verb stays in the base form. 'Didn't went' = double past marking — one of the most common errors. 'Hasn't gone...yesterday' combines present perfect with a specific past time — wrong. 'Wasn't go' is not a valid English structure.",
    lessonNumber: 7,
    sourceFolder: "Lesson 7 Tense and Aspecdt/p07-quiz",
    sourceFile: "Lesson 7 Tense and Aspecdt/p07-quiz/questions.js",
    originalId: 23,
  },

  {
    id: 68, type: "mc",
    bankId: "L08-Q23", examSection: "error-identification",
    stem: "One of these sentences has an error. Which sentence is correct?",
    options: {
      A: "The teaching at Oxford University professor gave a lecture.",
      B: "The professor gave a lecture teaching at Oxford University.",
      C: "The professor teaching at Oxford University gave a lecture.",
      D: "The at Oxford University teaching professor gave a lecture.",
    },
    correct: "C",
    explanation: "'Teaching at Oxford University' is a participial PHRASE (more than one word). Phrases must follow the noun they modify: *the professor teaching at Oxford University*. Option A wrongly places the entire phrase before 'professor' — only single-word participles can precede the noun. Option B places the phrase at the end of the sentence, where it describes the act of giving the lecture rather than identifying which professor. Option D splits the phrase, inserting the prepositional phrase in the wrong position.",
    lessonNumber: 8,
    sourceFolder: "Lesson 8/p08-quiz",
    sourceFile: "Lesson 8/p08-quiz/questions.js",
    originalId: 23,
  },

  {
    id: 69, type: "mc",
    bankId: "L05-Q50", examSection: "error-identification",
    stem: "Which sentence is correct?",
    options: {
      A: "Either the manager or the workers is coming.",
      B: "Either the manager or the workers are coming.",
      C: "Either the manager or the workers has coming.",
      D: "Either the manager or the workers comes.",
    },
    correct: "B",
    explanation: "Teacher's Insight: With 'either...or,' the verb agrees with the nearest subject. 'Workers' is nearest and plural, so 'are' is correct. This is called the proximity rule. / 「either...or」では、動詞は最も近い主語に一致します。「workers」が最も近く複数なので「are」が正解。これを近接ルールといいます。",
    lessonNumber: 5,
    sourceFolder: "Lesson 5/MPG2026_L05C_Quiz",
    sourceFile: "Lesson 5/MPG2026_L05C_Quiz/questions.js",
    originalId: 10,
  },

  {
    id: 70, type: "mc",
    bankId: "L07-Q24", examSection: "error-identification",
    stem: "One of these sentences has an error. Which sentence is correct?",
    options: {
      A: "If she will come, I will tell her.",
      B: "If she comes, I will tell her.",
      C: "If she would come, I will tell her.",
      D: "If she had come, I will tell her.",
    },
    correct: "B",
    explanation: "FIRST CONDITIONAL: If + PRESENT SIMPLE, will + base verb. Never use 'will' in the if-clause — this is one of the most common grammar errors. 'If she comes' (not 'will come') is the standard structure. The present simple in the if-clause already expresses a future condition.",
    lessonNumber: 7,
    sourceFolder: "Lesson 7 Tense and Aspecdt/p07-quiz",
    sourceFile: "Lesson 7 Tense and Aspecdt/p07-quiz/questions.js",
    originalId: 24,
  },


  // ── Drag & Drop ─────────────────────────────

  {
    id: 71, type: "dragdrop",
    bankId: "L01-Q20", examSection: "drag-and-drop",
    instruction: "Arrange the words to make a correct sentence.",
    blocks: ["The student", "reads", "a book"],
    correct: ["The student", "reads", "a book"],
    lessonNumber: 1,
    sourceFolder: "MPG2026_L01_Quiz",
    sourceFile: "MPG2026_L01_Quiz/questions.js",
    originalId: 20,
  },

  {
    id: 72, type: "dragdrop",
    bankId: "L02-Q24", examSection: "drag-and-drop",
    instruction: "Arrange the words to make a correct sentence.",
    blocks: ["The man", "standing by the door", "is", "my teacher"],
    correct: ["The man", "standing by the door", "is", "my teacher"],
    lessonNumber: 2,
    sourceFolder: "MPG2026_L02_Quiz",
    sourceFile: "MPG2026_L02_Quiz/questions.js",
    originalId: 24,
  },

  {
    id: 73, type: "dragdrop",
    bankId: "L03-Q23", examSection: "drag-and-drop",
    instruction: "Arrange the words to make a correct sentence.",
    blocks: ["They", "elected", "her", "the new president"],
    correct: ["They", "elected", "her", "the new president"],
    lessonNumber: 3,
    sourceFolder: "MPG2026_L03_Quiz",
    sourceFile: "MPG2026_L03_Quiz/questions.js",
    originalId: 23,
  },

  {
    id: 74, type: "dragdrop",
    bankId: "L01-Q23", examSection: "drag-and-drop",
    instruction: "Arrange the words to make a correct sentence.",
    blocks: ["The book", "on the table", "is", "mine"],
    correct: ["The book", "on the table", "is", "mine"],
    lessonNumber: 1,
    sourceFolder: "MPG2026_L01_Quiz",
    sourceFile: "MPG2026_L01_Quiz/questions.js",
    originalId: 23,
  },

  {
    id: 75, type: "dragdrop",
    bankId: "L04-Q21", examSection: "drag-and-drop",
    instruction: "Arrange the words to make a correct sentence.",
    blocks: ["I", "saw", "him", "crossing", "the street"],
    correct: ["I", "saw", "him", "crossing", "the street"],
    lessonNumber: 4,
    sourceFolder: "Lesson 4/MPG2026_L04_Quiz",
    sourceFile: "Lesson 4/MPG2026_L04_Quiz/questions.js",
    originalId: 21,
  },

  {
    id: 76, type: "dragdrop",
    bankId: "L05-Q19", examSection: "drag-and-drop",
    instruction: "Arrange the words to make a correct sentence.",
    blocks: ["I", "need", "another", "chair"],
    correct: ["I", "need", "another", "chair"],
    lessonNumber: 5,
    sourceFolder: "Lesson 5/MPG2026_L05A_Quiz",
    sourceFile: "Lesson 5/MPG2026_L05A_Quiz/questions.js",
    originalId: 19,
  },

  {
    id: 77, type: "dragdrop",
    bankId: "L06-Q35", examSection: "drag-and-drop",
    instruction: "Arrange the words to make a correct English sentence.",
    blocks: ["In", "spite", "of", "the", "rain", "the", "match", "continued"],
    correct: ["In", "spite", "of", "the", "rain", "the", "match", "continued"],
    lessonNumber: 6,
    sourceFolder: "Lesson6/p06-quiz",
    sourceFile: "Lesson6/p06-quiz/questions.js",
    originalId: 35,
  },

  {
    id: 78, type: "dragdrop",
    bankId: "L07-Q27", examSection: "drag-and-drop",
    instruction: "Arrange the words to make a correct English sentence.",
    fixedStart: ["By", "the", "time", "he"],
    blocks: ["arrived", "she", "had", "left"],
    correct: ["By", "the", "time", "he", "arrived", "she", "had", "left"],
    lessonNumber: 7,
    sourceFolder: "Lesson 7 Tense and Aspecdt/p07-quiz",
    sourceFile: "Lesson 7 Tense and Aspecdt/p07-quiz/questions.js",
    originalId: 27,
  },

  {
    id: 79, type: "dragdrop",
    bankId: "L09-Q14", examSection: "drag-and-drop",
    instruction: "Arrange the word blocks to make a correct phrase.",
    fixedStart: [],
    blocks: ["graduated", "which", "the school from", "she"],
    correct: ["the school from", "which", "she", "graduated"],
    explanation: "Correct phrase: 'the school from which she graduated.' This is the formal pattern 'preposition + which.' We say 'graduate from a school.'",
    lessonNumber: 9,
    sourceFolder: "Lesson 9/p09-quiz",
    sourceFile: "Lesson 9/p09-quiz/questions.js",
    originalId: 14,
  },

  {
    id: 80, type: "dragdrop",
    bankId: "L05-Q59", examSection: "drag-and-drop",
    instruction: "Arrange the words to make a correct sentence.",
    blocks: ["Neither", "the teacher", "nor", "the students", "were", "late"],
    correct: ["Neither", "the teacher", "nor", "the students", "were", "late"],
    lessonNumber: 5,
    sourceFolder: "Lesson 5/MPG2026_L05C_Quiz",
    sourceFile: "Lesson 5/MPG2026_L05C_Quiz/questions.js",
    originalId: 19,
  },

  {
    id: 81, type: "dragdrop",
    bankId: "L07-Q31", examSection: "drag-and-drop",
    instruction: "Arrange the words to make a correct English sentence.",
    fixedStart: ["If"],
    blocks: ["I", "had", "known", "I", "would", "have", "told", "you"],
    correct: ["If", "I", "had", "known", "I", "would", "have", "told", "you"],
    lessonNumber: 7,
    sourceFolder: "Lesson 7 Tense and Aspecdt/p07-quiz",
    sourceFile: "Lesson 7 Tense and Aspecdt/p07-quiz/questions.js",
    originalId: 31,
  },

  {
    id: 82, type: "dragdrop",
    bankId: "L08-Q25", examSection: "drag-and-drop",
    instruction: "Arrange the words to make a correct English sentence.",
    blocks: ["His", "ability", "to", "speak", "English", "helped", "him", "get", "the", "job"],
    correct: ["His", "ability", "to", "speak", "English", "helped", "him", "get", "the", "job"],
    lessonNumber: 8,
    sourceFolder: "Lesson 8/p08-quiz",
    sourceFile: "Lesson 8/p08-quiz/questions.js",
    originalId: 25,
  },

  {
    id: 83, type: "dragdrop",
    bankId: "L10-Q05", examSection: "drag-and-drop",
    instruction: "Arrange the words to make a correct sentence. One word is unnecessary.",
    blocks: ["than", "much", "This", "computer", "is", "my", "faster", "old", "very", "one"],
    correct: ["This", "computer", "is", "much", "faster", "than", "my", "old", "one"],
    lessonNumber: 10,
    sourceFolder: "Lesson 10/p10-quiz",
    sourceFile: "Lesson 10/p10-quiz/questions.js",
    originalId: 5,
  },

  {
    id: 84, type: "dragdrop",
    bankId: "L08-Q31", examSection: "drag-and-drop",
    instruction: "Arrange the words to make a correct English sentence.",
    blocks: ["The", "article", "written", "by", "three", "researchers", "attracted", "international", "attention"],
    correct: ["The", "article", "written", "by", "three", "researchers", "attracted", "international", "attention"],
    lessonNumber: 8,
    sourceFolder: "Lesson 8/p08-quiz",
    sourceFile: "Lesson 8/p08-quiz/questions.js",
    originalId: 31,
  },

  {
    id: 85, type: "dragdrop",
    bankId: "L11-Q21", examSection: "drag-and-drop",
    instruction: "「もし私があなただったら、その申し出を受けるでしょう。」\nArrange the words to complete the sentence. One word is unnecessary.",
    blocks: ["If", "were", "I", "you", "would", "accept", "the", "offer", "are", "I"],
    correct: ["If", "I", "were", "you", "I", "would", "accept", "the", "offer"],
    lessonNumber: 11,
    sourceFolder: "Lesson 11/p11-quiz",
    sourceFile: "Lesson 11/p11-quiz/questions.js",
    originalId: 21,
  },


  // ── Dictation ───────────────────────────────

  {
    id: 86, type: "dictation",
    bankId: "L01-Q25", examSection: "dictation",
    audio: "audio/q25.mp3",
    correct: "The student reads a book",
    note: "This is a basic SVO sentence.",
    lessonNumber: 1,
    sourceFolder: "MPG2026_L01_Quiz",
    sourceFile: "MPG2026_L01_Quiz/questions.js",
    originalId: 25,
  },

  {
    id: 87, type: "dictation",
    bankId: "L09-Q26", examSection: "dictation",
    audio: "audio/p09_q26.mp3",
    correct: "The town where she grew up has changed.",
    note: "'She grew up in the town' — the town is a location. Use 'where.' Alternatively: 'the town that she grew up in' or 'the town she grew up in.'",
    lessonNumber: 9,
    sourceFolder: "Lesson 9/p09-quiz",
    sourceFile: "Lesson 9/p09-quiz/questions.js",
    originalId: 26,
  },

  {
    id: 88, type: "dictation",
    bankId: "L11-Q28", examSection: "dictation",
    audio: "audio/p11_q28.mp3",
    correct: "If I had known the truth, I would have apologized.",
    note: "Past hypothetical: <em>If + had + past participle</em>, <em>would have + past participle</em>.",
    lessonNumber: 11,
    sourceFolder: "Lesson 11/p11-quiz",
    sourceFile: "Lesson 11/p11-quiz/questions.js",
    originalId: 28,
  },


  // ── Dictation + Analysis ────────────────────

  {
    id: 89, type: "dictation_analysis",
    bankId: "L01-Q30", examSection: "dictation-analysis",
    audio: "audio/q30.mp3",
    correct: "The man standing by the door is my teacher",
    analysisQuestion: "What is <em>standing</em>?",
    options: {
      A: "main verb",
      B: "adjective modifying man",
      C: "noun",
    },
    correctAnalysis: "B",
    explanation: "<em>Standing by the door</em> describes <em>man</em>.",
    note: "Listen for the participial phrase that modifies the subject.",
    lessonNumber: 1,
    sourceFolder: "MPG2026_L01_Quiz",
    sourceFile: "MPG2026_L01_Quiz/questions.js",
    originalId: 30,
  },

  {
    id: 90, type: "dictation_analysis",
    bankId: "L06-Q39", examSection: "dictation-analysis",
    audio: "audio/p06_q39.mp3",
    correct: "The letter was written in pencil, not with a pen.",
    analysisQuestion: "What is the difference between <em>in pencil</em> and <em>with a pen</em>?",
    options: {
      A: "There is no real difference — both are correct",
      B: "'In pencil' means the pencil is a medium; 'with a pen' means the pen is a tool",
      C: "'In pencil' is used for formal writing only",
    },
    correctAnalysis: "B",
    explanation: "IN pencil = medium (uncountable, no article) — the writing exists within the substance of pencil. WITH a pen = tool (countable, needs article 'a') — you hold the pen as an instrument. The grammar signals the frame: no article = medium = IN; article = tool = WITH.",
    note: "IN + no article = medium/substance. WITH + article = countable tool. The countability difference is the key.",
    lessonNumber: 6,
    sourceFolder: "Lesson6/p06-quiz",
    sourceFile: "Lesson6/p06-quiz/questions.js",
    originalId: 39,
  },

  {
    id: 91, type: "dictation_analysis",
    bankId: "L08-Q38", examSection: "dictation-analysis",
    audio: "audio/p08_q38.mp3",
    correct: "The company's rapid expansion surprised investors.",
    analysisQuestion: "Why is <em>expansion</em> used — not <em>expanded</em>?",
    options: {
      A: "Because 'expansion' is a noun and can be the head of the subject noun phrase",
      B: "Because 'expanded' is the wrong tense for this sentence",
      C: "Because 'expansion' sounds more formal than 'expanded'",
    },
    correctAnalysis: "A",
    explanation: "NOMINALIZATION: the subject of a sentence must be a noun or noun phrase, not a verb. 'The company's rapid expansion' is the subject — *expansion* (a noun) is its head. 'Expanded' is a past-tense verb; it cannot be the head of a noun phrase. When we nominalize 'the company expanded rapidly,' the verb 'expanded' becomes the noun 'expansion,' and the adverb 'rapidly' becomes the adjective 'rapid.' This transforms the whole event into a compact, portable noun phrase that can serve as subject, object, or complement.",
    note: "NOMINALIZATION: verb → noun; adverb → adjective. 'Expanded rapidly' → 'rapid expansion.' The subject position always requires a noun.",
    lessonNumber: 8,
    sourceFolder: "Lesson 8/p08-quiz",
    sourceFile: "Lesson 8/p08-quiz/questions.js",
    originalId: 38,
  },


  // ── Fill-in-the-Blank ───────────────────────

  {
    id: 92, type: "fillin",
    bankId: "L11-Q16", examSection: "fill-in-the-blank",
    stem: "「もっと自信があればいいのに。」\nI ________ I were more confident.",
    correct: ["wish", "Wish"],
    explanation: "After <em>wish</em>, use the past form ('were') to show the wish isn't true now.",
    lessonNumber: 11,
    sourceFolder: "Lesson 11/p11-quiz",
    sourceFile: "Lesson 11/p11-quiz/questions.js",
    originalId: 16,
  },

  {
    id: 93, type: "fillin",
    bankId: "L11-Q17", examSection: "fill-in-the-blank",
    stem: "「もっと早く出発していればよかったのに。」\n________ ________ I had left earlier.",
    correct: ["If only", "if only"],
    explanation: "<em>If only</em> introduces a stronger wish or regret; 'had left' (past perfect) refers to something that didn't happen in the past.",
    lessonNumber: 11,
    sourceFolder: "Lesson 11/p11-quiz",
    sourceFile: "Lesson 11/p11-quiz/questions.js",
    originalId: 17,
  },

  {
    id: 94, type: "fillin",
    bankId: "L11-Q19", examSection: "fill-in-the-blank",
    stem: "「彼はまるですべてを知っているかのように話す。」\nHe speaks ________ ________ he knew everything.",
    correct: ["as if", "As if"],
    explanation: "<em>As if + past form</em> introduces an imaginary comparison that the speaker doubts is true.",
    lessonNumber: 11,
    sourceFolder: "Lesson 11/p11-quiz",
    sourceFile: "Lesson 11/p11-quiz/questions.js",
    originalId: 19,
  },

  {
    id: 95, type: "fillin",
    bankId: "L11-Q20", examSection: "fill-in-the-blank",
    stem: "「私たちは急いだ。そうでなければ飛行機に乗り遅れていただろう。」\nWe hurried. ________, we would have missed the flight.",
    correct: ["Otherwise", "otherwise"],
    explanation: "<em>Otherwise</em> means 'if this had not happened' and introduces the imagined alternative result with 'would have + past participle'.",
    lessonNumber: 11,
    sourceFolder: "Lesson 11/p11-quiz",
    sourceFile: "Lesson 11/p11-quiz/questions.js",
    originalId: 20,
  },
];
